#
#
# Tencent is pleased to support the open source community by making
# Hippy available.
#
# Copyright (C) 2022 THL A29 Limited, a Tencent company.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#


name: voltron_renderer
description: voltron renderer
version: 0.0.23
homepage: https://hippyjs.org
repository: https://github.com/Tencent/Hippy

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=3.3.8"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.10
  sprintf: ^6.0.0
  provider: ^6.0.0
  pull_to_refresh: ^2.0.0
  collection: ^1.15.0
  path: ^1.8.0
  gradient_like_css: ^1.0.1
  keyboard_utils: ^1.3.4
  webview_flutter: ^4.2.0
  waterfall_flow: ^3.0.2
  charset: ^1.1.0
  ffi: ^2.0.0
  voltron_ffi: 0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.2.1
  mockito: ^5.3.0


