#name: '[debug] build tests'
#
#on:
#  pull_request:
#    branches:
#      - main
#      - master
#    paths:
#      - 'examples/hippy-*-demo/scripts/**'
#      - 'examples/hippy-*-demo/package.json'
#
#jobs:
#  debug_tests:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node: [ 14.x, 16.x ]
#    steps:
#      - uses: actions/checkout@v2
#      - name: setup-node
#        uses: actions/setup-node@master
#        with:
#          node-version: ${{ matrix.node }}
#          registry-url: https://npm.pkg.github.com
#      - name: initial example
#        run: npm install && npm run init:example hippy-react-demo
#      - name: debug
#        run: npm run debugexample hippy-react-demo dev
