#name: '[debug] build tests'
#
#on:
#  pull_request:
#    branches:
#      - main
#      - master
#    paths-ignore:
#      - 'examples/hippy-*-demo/scripts/**'
#      - 'examples/hippy-*-demo/package.json'
#
#jobs:
#  debug_tests:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        node: [ 14.x, 16.x ]
#    steps:
#      - name: Debug Test Bypass
#        run: |
#          echo "No debug test required"
