name: buildios

on: [ push, pull_request ]

jobs:
  buildios:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: buildexample
        run: pushd examples/ios-demo && xcodebuild build -destination 'name=iPhone 11' -scheme 'HippyDemo' && popd
