name: '[iOS] build iOS native example'

on:
  push:
    paths:
      - 'framework/js/ios/**'
    branches:
      # Push events on main branch
      - main
      # Push events on master branch
      - master
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - 'framework/js/ios/**'
    branches:
      # Pull request events to main branch
      - main
      # Pull request events to master branch
      - master
    tags-ignore:
      - '**'

jobs:
  buildios:
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2
      - name: buildexample
        run: |
          # https://github.com/actions/virtual-environments/issues/4180
          # Xcode_13 will be selected on October, 18, so we need to set to xcode13 manually before that day.
          sudo xcode-select --switch '/Applications/Xcode_13.0.app/'
          pushd examples/ios-demo && xcodebuild build -destination 'name=iPhone 11' -scheme 'HippyDemo' && popd
